language: generic
sudo: required
env:
  global:
    - YOUTRACK_VERSION=2017.4
    - YOUTRACK_BUILD=39406
services:
  - docker
script:
  # prepare qemu (https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/)
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t gregoireweber/youtrack-arm:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag gregoireweber/youtrack-arm:latest gregoireweber/youtrack-arm:"$YOUTRACK_VERSION"."YOUTRACK_BUILD"-"$TRAVIS_BUILD_NUMBER";
    docker tag gregoireweber/youtrack-arm:latest gregoireweber/youtrack-arm:"$YOUTRACK_VERSION"."YOUTRACK_BUILD";
    docker tag gregoireweber/youtrack-arm:latest gregoireweber/youtrack-arm:"$YOUTRACK_VERSION";
    docker push gregoireweber/youtrack-arm:latest;
    docker push gregoireweber/youtrack-arm:"$YOUTRACK_VERSION"."YOUTRACK_BUILD"-"$TRAVIS_BUILD_NUMBER";
    docker push gregoireweber/youtrack-arm:"$YOUTRACK_VERSION"."YOUTRACK_BUILD";
    docker push gregoireweber/youtrack-arm:"$YOUTRACK_VERSION";
  fi