language: generic
sudo: required
env:
  global:
    - YOUTRACK_VERSION=2017.4
    - YOUTRACK_BUILD=39406
services:
  - docker
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t gregoireweber/youtrack-arm:latest .